### ISSUE TITLE
Redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by cdunklau** [pound-python/infobob-docker#2]
The HSTS stuff in the nginx container is ineffective until such a redirect is implemented.

**Comment by ssbr** [comment]
Ineffective? it should AFAIK just be bonus (supporting clients that don't support HSTS or haven't yet visited the site under HTTPS / haven't received the preloaded HSTS directive). Still a good idea though.

**Comment by cdunklau** [comment]
Fair enough, didn't really think that through :)

**Comment by cdunklau** [comment]
This is obsolete since the move to rproxy
